[package]
name = "quiche-host"
version = "0.1.0"
edition = "2021"

[dependencies]
quiche-compiler = { path = "../quiche-compiler" }

[[bin]]
name = "quiche-host"
path = "src/main.rs"

[dev-dependencies]
tempfile = "3.24.0"
