[package]
name = "parsley"
version = "0.1.0"
edition = "2024"

# Break out of any parent workspace
[workspace]

[dependencies]
quiche-runtime = { path = "../quiche-runtime" }

[lib]
path = "src/lib.rs"