[workspace]
members = [
    "crates/quiche-compiler",
    "crates/quiche-host",
    "crates/metaquiche-native",
    "crates/quiche-runtime",
    "crates/parsley-qrs", "crates/metaquiche-host",
]
resolver = "2"
