[package]
name = "quiche-runtime"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
metaquiche-shared = { path = "../metaquiche-shared" }
quiche-parser = { path = "../quiche-parser" }
regex = "1"
