[package]
name = "crates/parsley_qrs"
version = "0.1.0"
edition = "2024"

# Break out of any parent workspace
[workspace]

[build-dependencies]
quiche_compiler = { path = "/Users/jagtesh/.gemini/antigravity/playground/exo-kuiper/quiche/crates/compiler" }

[dependencies]

[lib]
path = "src/lib.rs"
