[package]
name = "quiche-to-metaquiche"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
ruff_python_ast = { git = "https://github.com/astral-sh/ruff" }
metaquiche-host = { path = "../metaquiche-host" }
